apiVersion: v1
kind: Service
metadata:
  name: aibackend
  labels:
    app: aibackend
spec:
  selector:
    app: aibackend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibackend
  labels:
    app: aibackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aibackend
  template:
    metadata:
      labels:
        app: aibackend
    spec:
      serviceAccountName: aibackend
      containers:
      - name: aibackend
        image: gcr.io/PROJECT_ID/aibackend:latest
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "v1.0.0"
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: PROJECT_ID
        - name: GOOGLE_CLOUD_REGION
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: REGION
        - name: VERTEX_AI_LOCATION
          value: "us-central1"
        - name: VERTEX_AI_MODEL
          value: "gemini-1.5-pro"
        - name: ACCOUNTS_DB_URI
          valueFrom:
            configMapKeyRef:
              name: accounts-db-config
              key: ACCOUNTS_DB_URI
        - name: LEDGER_DB_URI
          valueFrom:
            configMapKeyRef:
              name: ledger-db-config
              key: LEDGER_DB_URI
        - name: LOCAL_ROUTING_NUM
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: LOCAL_ROUTING_NUM
        - name: PUB_KEY_PATH
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: PUB_KEY_PATH
        - name: MAX_RETRIES
          value: "1"
        - name: INSIGHT_EXPIRY_DAYS
          value: "7"
        - name: MAX_INSIGHTS_PER_USER
          value: "50"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: jwt-key
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: jwt-key
        secret:
          secretName: jwt-key
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aibackend
  annotations:
    iam.gke.io/gcp-service-account: aibackend@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aibackend-config
data:
  VERTEX_AI_LOCATION: "us-central1"
  VERTEX_AI_MODEL: "gemini-1.5-pro"
  MAX_RETRIES: "1"
  INSIGHT_EXPIRY_DAYS: "7"
  MAX_INSIGHTS_PER_USER: "50"
